<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>br.com.joaofelipefaria.hex</groupId>
	<artifactId>mapdata-core</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<!-- Set Java version to 17 -->
		<maven.compiler.release>17</maven.compiler.release>
		<java.version>17</java.version>
	</properties>
	<build>
		<plugins>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.13.0</version>
				<configuration>
					<release>${maven.compiler.release}</release>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>