server:
  port: 80

spring:
  application:
    name: simple-api-gateway

gateway:
  routes:
    mapdata: http://localhost:8081
    mapdata2: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info